# Generated by Django 5.0.7 on 2024-07-19 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='Customer',
            name='full_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seller',
            name='full_name',
            field=models.CharField(default='default', max_length=100),
            preserve_default=False,
        ),
    ]
