# Generated by Django 5.0.7 on 2024-07-20 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0004_user_groups_user_is_superuser_user_user_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='Customer',
            name='phone_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='seller',
            name='phone_number',
            field=models.CharField(max_length=10),
        ),
    ]
