# Generated by Django 5.0.7 on 2024-07-23 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippinginfo',
            name='paymentType',
            field=models.CharField(choices=[('Bank Transfer', 'Bank Transfer'), ('Credit Card', 'Credit Card'), ('UPI', 'UPI')], default='Bank Transfer', max_length=50),
        ),
    ]
