# Generated by Django 5.0.7 on 2024-07-27 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0004_shippinginfo_customer'),
        ('Seller', '0002_alter_product_category_alter_product_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippinginfo',
            name='order',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Seller.order'),
        ),
    ]
