# Generated by Django 5.0.7 on 2024-07-27 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('null', 'Select Category'), ('oil', 'Oil painting'), ('acrylic', 'Acrylic painting'), ('water', 'water painting'), ('pastel', 'pastel painting'), ('spray', 'spray painting'), ('other', 'other painting')], default='null', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('null', 'Select Size'), ('4x8', '4 x 8 inches (10.16 x 20.32 cm) - Small'), ('8x10', '8 x 10 inches (20.32 x 25.4 cm) - Medium'), ('16x20', '16 x 20 inches (40.64 x 50.8 cm) - Large'), ('24x30', '24 x 30 inches (60.96 x 76.2 cm) - Large')], default='null', max_length=6),
        ),
    ]
