# Generated by Django 5.1 on 2024-09-12 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0007_orderitem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('rejected', 'Rejected'), ('accepted', 'Accepted'), ('packed', 'Packed'), ('shipped', 'Shipped'), ('delivered', 'Delivered')], default='accepted', max_length=10),
        ),
    ]
